### ISSUE TITLE
terminate called without an active exception if ASSERT failed

### ISSUE THREAD

**Issue by GerdHirsch** [Cute-Test/Issues#7]
### Expected Behavior

ASSERT failed, red bar
### Actual Behavior
output:
```
#beginning AllTests 1

#starting bugReportCute
terminate called without an active exception
      6 [main] GateCuteTest 9072 cygwin_exception::open_stackdumpfile: Dumping stack trace to GateCuteTest.exe.stackdump
```

### CUTE or CUTE Eclipse Plug-in Version, Operating System and Compiler
```
CUTE C++ Unit Testing Easier	5.7.2.201907101456	ch.hsr.ifs.cute.feature.feature.group	IFS Institute for Software
eclipse: Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
Building file: ../src/BugReportCute.cpp
Invoking: Cygwin C++ Compiler
g++ -std=c++0x -I"C:\Users\Gerd\git\bitbucket\skippyqueue\GateCuteTest\cute" -I"C:\Users\Gerd\git\bitbucket\skippyqueue\Gate\include" -O0 -g3 -Wall -c -fmessage-length=0 --version -MMD -MP -MF"src/BugReportCute.d" -MT"src/BugReportCute.o" -o "src/BugReportCute.o" "../src/BugReportCute.cpp"
g++ (GCC) 7.4.0
```
[bugReport.txt](https://github.com/Cute-Test/Issues/files/3563952/bugReport.txt)

windows 10 home version 1903 Build 18362.295

The more we know about your setup, the easier it will be for us to reproduce the problem.

**Comment by GerdHirsch** [comment]
same problem with older versions of gcc and CUTE

**Comment by Darnor** [comment]
Thank you for the report.

This happens because CUTE will throw an `cute::test_failure` exception in its ASSERT on failure and the `std::thread t(demoSUTThread)` has not yet been joined leading to the `std::terminate()` call in the `std::tread` destructor.

To get your desired result you could do something along the lines of:
```
try {
	ASSERT(a.load(memory_order_relaxed) == 1);
} catch (...) {
	gate.store(0, memory_order_relaxed);
	t.join();
	ASSERTM("a.load(memory_order_relaxed) == 1", false);
}
```

**Comment by tcorbat** [comment]
Alternatively, you can use a RAII wrapper for the `std::thread`. That's an approach I'd suggest anyway when you work with resource that need to closed - or joined/detached as in the case of `std::thread`. Anthony Williams suggests to use a `scoped_thread` as available in [Boost](https://www.boost.org/doc/libs/1_71_0/doc/html/thread/ScopedThreads.html). In this way you can circumvent the approach using a catch-all clause.

Btw. regarding your test, I guess you are aware that there is no guarantee that your test is ever green with relaxed memory order. Even the call of `yield` is no guarantee, as the independent operations can be reordered with respect to the visible side-effects.

Best Regards
Thomas

**Comment by PeterSommerlad** [comment]
or: https://github.com/josuttis/jthread or its fork https://github.com/anthonywilliams/jthread

both authors collaborated on c++20's jthread specification

**Comment by PeterSommerlad** [comment]
This is not a defect in Cevelop or CUTE.
